// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ottubmkmjuukffhsdabp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90dHVibWttanV1a2ZmaHNkYWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NDUyOTQsImV4cCI6MjA4MzIyMTI5NH0.gcho2mABGnTq1cn20TAVCr9SZfCLqkPecEJ6wzFHvbI";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);